spring:
  application:
    name: mall-gateway
  cloud:
    gateway:
      routes:
        - id: test
          url: https://www.baidu.com
          predicates:
            - Query : url,baidu
        - id: qq_route
            url: https://www.qq.com
            predicates:
              - Query: url,qq
server:
  port: 88

